from app.api.routes import (
    agents,
    alerts,
    artifacts,
    audit,
    auth,
    correlation,
    dashboard,
    detection,
    events,
    evidence,
    forensics,
    health,
    integrations,
    investigations,
    policy,
    reports,
    sessions,
    telemetry,
)
from app.api.routes import adapters
from app.api.routes import demo

__all__ = [
    "agents",
    "alerts",
    "artifacts",
    "audit",
    "auth",
    "correlation",
    "dashboard",
    "detection",
    "events",
    "evidence",
    "forensics",
    "health",
    "integrations",
    "investigations",
    "policy",
    "reports",
    "sessions",
    "telemetry",
    "adapters",
    "demo"
]
