from __future__ import annotations

from enum import StrEnum


class EventType(StrEnum):
    AGENT_STARTED = "AGENT_STARTED"
    AGENT_COMPLETED = "AGENT_COMPLETED"

    USER_REQUEST = "USER_REQUEST"
    AGENT_RESPONSE = "AGENT_RESPONSE"
    AGENT_DECISION = "AGENT_DECISION"

    TOOL_CALL = "TOOL_CALL"
    TOOL_RESULT = "TOOL_RESULT"

    CONTENT_RETRIEVED = "CONTENT_RETRIEVED"
    UNTRUSTED_CONTENT = "UNTRUSTED_CONTENT"
    PROMPT_INJECTION_DETECTED = "PROMPT_INJECTION_DETECTED"

    SENSITIVE_ACTION_ATTEMPTED = "SENSITIVE_ACTION_ATTEMPTED"

    POLICY_EVALUATION = "POLICY_EVALUATION"
    POLICY_VIOLATION = "POLICY_VIOLATION"

    TOOL_BLOCKED = "TOOL_BLOCKED"
    TOOL_ALLOWED = "TOOL_ALLOWED"

    ERROR = "ERROR"

    AUDIT_LOG = "AUDIT_LOG"


class EventStatus(StrEnum):
    RECEIVED = "RECEIVED"
    REQUESTED = "REQUESTED"
    STARTED = "STARTED"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    ATTEMPTED = "ATTEMPTED"
    BLOCKED = "BLOCKED"
    ALLOWED = "ALLOWED"
    SIMULATED = "SIMULATED"
    COMPLETED = "COMPLETED"


class EventSeverity(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class EventRelationshipType(StrEnum):
    PARENT = "PARENT"
    RELATED = "RELATED"
    CAUSED_BY = "CAUSED_BY"
    FOLLOWS = "FOLLOWS"
    DERIVED_FROM = "DERIVED_FROM"
