"""Create AgentTrace initial database schema.

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-09-18
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0001_initial_schema"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Create the initial AgentTrace schema."""

    # ------------------------------------------------------------------
    # Users
    # ------------------------------------------------------------------
    op.create_table(
        "users",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=False),
            primary_key=True,
            nullable=False,
        ),
        sa.Column(
            "email",
            sa.String(length=320),
            nullable=False,
        ),
        sa.Column(
            "password_hash",
            sa.String(length=255),
            nullable=False,
        ),
        sa.Column(
            "display_name",
            sa.String(length=255),
            nullable=False,
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            server_default=sa.true(),
        ),
        sa.Column(
            "role",
            sa.String(length=50),
            nullable=False,
            server_default="analyst",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.UniqueConstraint(
            "email",
            name="uq_users_email",
        ),
    )

    # ------------------------------------------------------------------
    # Agents
    # ------------------------------------------------------------------
    op.create_table(
        "agents",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=False),
            primary_key=True,
            nullable=False,
        ),
        sa.Column(
            "agent_id",
            sa.String(length=255),
            nullable=False,
        ),
        sa.Column(
            "name",
            sa.String(length=255),
            nullable=False,
        ),
        sa.Column(
            "description",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "provider",
            sa.String(length=100),
            nullable=False,
        ),
        sa.Column(
            "provider_display_name",
            sa.String(length=255),
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.String(length=50),
            nullable=False,
        ),
        sa.Column(
            "risk_score",
            sa.Integer(),
            nullable=False,
            server_default="0",
        ),
        sa.Column(
            "risk_level",
            sa.String(length=50),
            nullable=False,
            server_default="low",
        ),
        sa.Column(
            "last_seen",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "integration_type",
            sa.String(length=100),
            nullable=True,
        ),
        sa.Column(
            "capabilities",
            postgresql.JSONB(),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.UniqueConstraint(
            "agent_id",
            name="uq_agents_agent_id",
        ),
    )

    # ------------------------------------------------------------------
    # Integrations
    # ------------------------------------------------------------------
    op.create_table(
        "integrations",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=False),
            primary_key=True,
            nullable=False,
        ),
        sa.Column(
            "agent_id",
            postgresql.UUID(as_uuid=False),
            sa.ForeignKey(
                "agents.id",
                name="fk_integrations_agent_id_agents",
                ondelete="CASCADE",
            ),
            nullable=False,
        ),
        sa.Column(
            "integration_type",
            sa.String(length=100),
            nullable=False,
        ),
        sa.Column(
            "provider",
            sa.String(length=100),
            nullable=False,
        ),
        sa.Column(
            "endpoint",
            sa.String(length=2048),
            nullable=True,
        ),
        sa.Column(
            "api_key_reference",
            sa.String(length=255),
            nullable=True,
        ),
        sa.Column(
            "environment",
            sa.String(length=50),
            nullable=False,
            server_default="local",
        ),
        sa.Column(
            "status",
            sa.String(length=50),
            nullable=False,
        ),
        sa.Column(
            "configuration",
            postgresql.JSONB(),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
    )

    # ------------------------------------------------------------------
    # Sessions
    # ------------------------------------------------------------------
    op.create_table(
        "sessions",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=False),
            primary_key=True,
            nullable=False,
        ),
        sa.Column(
            "session_id",
            sa.String(length=255),
            nullable=False,
        ),
        sa.Column(
            "agent_id",
            postgresql.UUID(as_uuid=False),
            sa.ForeignKey(
                "agents.id",
                name="fk_sessions_agent_id_agents",
                ondelete="CASCADE",
            ),
            nullable=False,
        ),
        sa.Column(
            "provider",
            sa.String(length=100),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.String(length=50),
            nullable=False,
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "ended_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "duration",
            sa.Float(),
            nullable=True,
        ),
        sa.Column(
            "event_count",
            sa.Integer(),
            nullable=False,
            server_default="0",
        ),
        sa.Column(
            "alert_count",
            sa.Integer(),
            nullable=False,
            server_default="0",
        ),
        sa.Column(
            "risk_score",
            sa.Integer(),
            nullable=False,
            server_default="0",
        ),
        sa.Column(
            "risk_level",
            sa.String(length=50),
            nullable=False,
            server_default="low",
        ),
        sa.Column(
            "scenario",
            sa.String(length=255),
            nullable=True,
        ),
        sa.Column(
            "investigation_id",
            postgresql.UUID(as_uuid=False),
            nullable=True,
        ),
        sa.Column(
            "metadata",
            postgresql.JSONB(),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.UniqueConstraint(
            "session_id",
            name="uq_sessions_session_id",
        ),
    )

    # ------------------------------------------------------------------
    # Investigations
    #
    # Session -> Investigation is intentionally added after both tables
    # exist. This avoids the circular table-creation dependency.
    # ------------------------------------------------------------------
    op.create_table(
        "investigations",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=False),
            primary_key=True,
            nullable=False,
        ),
        sa.Column(
            "session_id",
            postgresql.UUID(as_uuid=False),
            sa.ForeignKey(
                "sessions.id",
                name="fk_investigations_session_id_sessions",
                ondelete="CASCADE",
            ),
            nullable=False,
        ),
        sa.Column(
            "agent_id",
            postgresql.UUID(as_uuid=False),
            sa.ForeignKey(
                "agents.id",
                name="fk_investigations_agent_id_agents",
                ondelete="CASCADE",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.String(length=50),
            nullable=False,
        ),
        sa.Column(
            "risk_score",
            sa.Integer(),
            nullable=False,
            server_default="0",
        ),
        sa.Column(
            "risk_level",
            sa.String(length=50),
            nullable=False,
            server_default="low",
        ),
        sa.Column(
            "scenario",
            sa.String(length=255),
            nullable=True,
        ),
        sa.Column(
            "verdict_type",
            sa.String(length=100),
            nullable=True,
        ),
        sa.Column(
            "attack_vector",
            sa.String(length=255),
            nullable=True,
        ),
        sa.Column(
            "impact",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "sensitive_action_attempted",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
        sa.Column(
            "sensitive_action_executed",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
        sa.Column(
            "policy_violation",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
        sa.Column(
            "action_blocked",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
        sa.Column(
            "external_transmission",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
        sa.Column(
            "summary",
            postgresql.JSONB(),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column(
            "graph",
            postgresql.JSONB(),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
    )

    op.create_index(
        "ix_investigations_session_id",
        "investigations",
        ["session_id"],
    )
    op.create_index(
        "ix_investigations_agent_id",
        "investigations",
        ["agent_id"],
    )

    # Add the reverse/session lookup FK after investigations exists.
    op.create_foreign_key(
        "fk_sessions_investigation_id_investigations",
        "sessions",
        "investigations",
        ["investigation_id"],
        ["id"],
        ondelete="SET NULL",
    )

    # ------------------------------------------------------------------
    # Events
    # ------------------------------------------------------------------
    op.create_table(
        "events",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=False),
            primary_key=True,
            nullable=False,
        ),
        sa.Column(
            "event_id",
            sa.String(length=255),
            nullable=False,
        ),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "session_id",
            postgresql.UUID(as_uuid=False),
            sa.ForeignKey(
                "sessions.id",
                name="fk_events_session_id_sessions",
                ondelete="CASCADE",
            ),
            nullable=False,
        ),
        sa.Column(
            "agent_id",
            postgresql.UUID(as_uuid=False),
            sa.ForeignKey(
                "agents.id",
                name="fk_events_agent_id_agents",
                ondelete="CASCADE",
            ),
            nullable=False,
        ),
        sa.Column(
            "provider",
            sa.String(length=100),
            nullable=False,
        ),
        sa.Column(
            "event_type",
            sa.String(length=100),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.String(length=50),
            nullable=False,
        ),
        sa.Column(
            "tool",
            sa.String(length=255),
            nullable=True,
        ),
        sa.Column(
            "source",
            sa.String(length=255),
            nullable=True,
        ),
        sa.Column(
            "severity",
            sa.String(length=50),
            nullable=False,
        ),
        sa.Column(
            "details",
            postgresql.JSONB(),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column(
            "metadata",
            postgresql.JSONB(),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column(
            "parent_event_id",
            sa.String(length=255),
            nullable=True,
        ),
        sa.Column(
            "related_event_id",
            sa.String(length=255),
            nullable=True,
        ),
        sa.Column(
            "trace_id",
            sa.String(length=255),
            nullable=True,
        ),
        sa.Column(
            "span_id",
            sa.String(length=255),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.UniqueConstraint(
            "event_id",
            name="uq_events_event_id",
        ),
    )

    op.create_index(
        "ix_events_session_timestamp",
        "events",
        ["session_id", "timestamp"],
    )
    op.create_index(
        "ix_events_agent_timestamp",
        "events",
        ["agent_id", "timestamp"],
    )
    op.create_index(
        "ix_events_event_type",
        "events",
        ["event_type"],
    )

    # ------------------------------------------------------------------
    # Alerts
    # ------------------------------------------------------------------
    op.create_table(
        "alerts",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=False),
            primary_key=True,
            nullable=False,
        ),
        sa.Column(
            "alert_id",
            sa.String(length=255),
            nullable=False,
        ),
        sa.Column(
            "agent_id",
            postgresql.UUID(as_uuid=False),
            sa.ForeignKey(
                "agents.id",
                name="fk_alerts_agent_id_agents",
                ondelete="CASCADE",
            ),
            nullable=False,
        ),
        sa.Column(
            "session_id",
            postgresql.UUID(as_uuid=False),
            sa.ForeignKey(
                "sessions.id",
                name="fk_alerts_session_id_sessions",
                ondelete="CASCADE",
            ),
            nullable=True,
        ),
        sa.Column(
            "investigation_id",
            postgresql.UUID(as_uuid=False),
            sa.ForeignKey(
                "investigations.id",
                name="fk_alerts_investigation_id_investigations",
                ondelete="CASCADE",
            ),
            nullable=True,
        ),
        sa.Column(
            "title",
            sa.String(length=255),
            nullable=False,
        ),
        sa.Column(
            "description",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "severity",
            sa.String(length=50),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.String(length=50),
            nullable=False,
        ),
        sa.Column(
            "detector_id",
            sa.String(length=255),
            nullable=True,
        ),
        sa.Column(
            "metadata",
            postgresql.JSONB(),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.UniqueConstraint(
            "alert_id",
            name="uq_alerts_alert_id",
        ),
    )

    # ------------------------------------------------------------------
    # Evidence
    # ------------------------------------------------------------------
    op.create_table(
        "evidence",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=False),
            primary_key=True,
            nullable=False,
        ),
        sa.Column(
            "investigation_id",
            postgresql.UUID(as_uuid=False),
            sa.ForeignKey(
                "investigations.id",
                name="fk_evidence_investigation_id_investigations",
                ondelete="CASCADE",
            ),
            nullable=False,
        ),
        sa.Column(
            "event_id",
            postgresql.UUID(as_uuid=False),
            sa.ForeignKey(
                "events.id",
                name="fk_evidence_event_id_events",
                ondelete="SET NULL",
            ),
            nullable=True,
        ),
        sa.Column(
            "evidence_type",
            sa.String(length=100),
            nullable=False,
        ),
        sa.Column(
            "title",
            sa.String(length=255),
            nullable=False,
        ),
        sa.Column(
            "description",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "storage_uri",
            sa.String(length=2048),
            nullable=True,
        ),
        sa.Column(
            "sha256",
            sa.String(length=64),
            nullable=True,
        ),
        sa.Column(
            "content",
            postgresql.JSONB(),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column(
            "metadata",
            postgresql.JSONB(),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
    )

    op.create_index(
        "ix_evidence_investigation_id",
        "evidence",
        ["investigation_id"],
    )

    # ------------------------------------------------------------------
    # Policies
    # ------------------------------------------------------------------
    op.create_table(
        "policies",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=False),
            primary_key=True,
            nullable=False,
        ),
        sa.Column(
            "name",
            sa.String(length=255),
            nullable=False,
        ),
        sa.Column(
            "description",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.String(length=50),
            nullable=False,
            server_default="active",
        ),
        sa.Column(
            "action",
            sa.String(length=50),
            nullable=False,
        ),
        sa.Column(
            "priority",
            sa.Integer(),
            nullable=False,
            server_default="100",
        ),
        sa.Column(
            "rules",
            postgresql.JSONB(),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column(
            "metadata",
            postgresql.JSONB(),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
    )

    # ------------------------------------------------------------------
    # Reports
    # ------------------------------------------------------------------
    op.create_table(
        "reports",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=False),
            primary_key=True,
            nullable=False,
        ),
        sa.Column(
            "investigation_id",
            postgresql.UUID(as_uuid=False),
            sa.ForeignKey(
                "investigations.id",
                name="fk_reports_investigation_id_investigations",
                ondelete="CASCADE",
            ),
            nullable=False,
        ),
        sa.Column(
            "report_type",
            sa.String(length=100),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.String(length=50),
            nullable=False,
        ),
        sa.Column(
            "title",
            sa.String(length=255),
            nullable=False,
        ),
        sa.Column(
            "content",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "storage_uri",
            sa.String(length=2048),
            nullable=True,
        ),
        sa.Column(
            "metadata",
            postgresql.JSONB(),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
    )

    op.create_index(
        "ix_reports_investigation_id",
        "reports",
        ["investigation_id"],
    )


def downgrade() -> None:
    """Drop the AgentTrace initial database schema."""

    op.drop_index(
        "ix_reports_investigation_id",
        table_name="reports",
    )
    op.drop_table("reports")

    op.drop_table("policies")

    op.drop_index(
        "ix_evidence_investigation_id",
        table_name="evidence",
    )
    op.drop_table("evidence")

    op.drop_table("alerts")

    op.drop_index(
        "ix_events_event_type",
        table_name="events",
    )
    op.drop_index(
        "ix_events_agent_timestamp",
        table_name="events",
    )
    op.drop_index(
        "ix_events_session_timestamp",
        table_name="events",
    )
    op.drop_table("events")

    op.drop_constraint(
        "fk_sessions_investigation_id_investigations",
        "sessions",
        type_="foreignkey",
    )

    op.drop_index(
        "ix_investigations_agent_id",
        table_name="investigations",
    )
    op.drop_index(
        "ix_investigations_session_id",
        table_name="investigations",
    )
    op.drop_table("investigations")

    op.drop_table("sessions")

    op.drop_table("integrations")
    op.drop_table("agents")
    op.drop_table("users")
